### ISSUE TITLE
Option all(): error with factor variables

### ISSUE THREAD

**Issue by fbittmann** [jluchman/domin#12]
Error message when using factor variables with the all() option.

Running: Stata 16.1MP
Domin: version 3.5.1
Moremata: 27jan2022

Minimal example:

```

. sysuse auto, clear
(1978 Automobile Data)

. domin price mpg weight turn, all(i.foreign)
                 stata():  3598  Stata returned error
           domin_2mata():     -  function returned error
                 <istmt>:     -  function returned error
r(3598);
```

Thanks for this ado, I use it all the time!

**Comment by fmg-jluchman** [comment]
Many thanks for the report, @fbittmann, and can reproduce the error.

It's an issue with the new 'built-in' `regress` command and, if you need to avoid getting the error while I patch it, can be accommodated with:

`domin price mpg weight turn, all(i.foreign) reg(regress) fitstat(e(r2))`

using the same model as the example.
