### ISSUE TITLE
Question about domin in relation to non-linear models

### ISSUE THREAD

**Issue by Ellesaere** [jluchman/domin#3]
Dear Mr. Luchman,

Thank you for this great command. I have one question however. You refer to a paper by Grömping (2007), https://www.tandfonline.com/doi/abs/10.1198/000313007X188252, in relation to the workings of this command. However, as far as I understand, that paper only refers to linear models. Is there any source on applying these methods to non-linear models (such as the glm for example)?

Kind Regards,

Tom

**Comment by jluchman** [comment]
Hi Tom,

  In short, you can and a more complete response is available on [Statalist](https://www.statalist.org/forums/forum/general-stata-discussion/general/1607459-is-there-any-way-in-stata-to-determine-relative-importance-explained-variation-of-variables-in-nonlinear-models).

  Tom, I realize you were the poster on Statalist as well.  I have included this link here for others with a similar question/for posterity.

- joe
