### ISSUE TITLE
Which mi_dom

### ISSUE THREAD

**Issue by ericmelse** [jluchman/domin#9]
Dear Joseph,
After installing `domin version 3.5.0 `, I used `which` to prompt the version information of `mi_dom`. This is the result:
```
. which mi_dom
*! fitdom version 0.0.0  8/14/2023 Joseph N. Luchman
```
It appears that you have edited the `fitdom.ado` file for `mi_dom` but did not update the version information.
Easy to correct.

And many thanks again for your good work on `domin`

**Comment by jluchman** [comment]
Many thanks for the report @ericmelse! 

Will work to submit a fix.
